### ISSUE TITLE
Gradlew tasks not working

### ISSUE THREAD

**Issue by RomuloPBenedetti** [AtomBuild/atom-build-gradle#13]
Command failed: /home/romulo/CropModelsUFSM/Github(git)/CropModelsUFSM/gradlew tasks
/bin/sh: 1: Syntax error: word unexpected (expecting ")")
Hide Stack Trace
Error: Command failed: /home/romulo/CropModelsUFSM/Github(git)/CropModelsUFSM/gradlew tasks
/bin/sh: 1: Syntax error: word unexpected (expecting ")")
    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

Some shell parsing problem maybe?

**Comment by noseglid** [comment]
Ah, I'm willing to bet the problem is with the folder name `Github(git)`, could you try from a folder which does not have paranthesis?
If that is the case, it should probably be escaped properly.

**Comment by RomuloPBenedetti** [comment]
Yes, I've removed parenthesis for now, I would suggest single quoting paths as it will guaranty no special meaning to any character. 
![spectacle m11554](https://cloud.githubusercontent.com/assets/12467382/17903156/ca99940c-6940-11e6-9159-0b898538da9b.png)

**Comment by noseglid** [comment]
Cool. Thanks for the report
