### ISSUE TITLE
Error when project folder contains spaces

### ISSUE THREAD

**Issue by YtvwlD** [AtomBuild/atom-build-gradle#17]
This bug in `build-gradle` only occurs when using the gradle wrapper.

```
Error: Command failed: /home/user/path with spaces/gradlew tasks
/bin/sh: 1: /home/user/path: not found
    at ChildProcess.exithandler (child_process.js:223:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by YtvwlD** [comment]
Oh, this seems to be the same issue as #13 and #10.
